import { IStatus } from '../types';
import { ICON_ID } from './icons';

export const STATUS_ID = {
  FLEXED: 1,
  PETRIFIED: 2,
  STONE_SKIN: 3,
  BURNED: 4,
  FROZEN: 5,
  BATTLE_FURY_1: 6,
  BATTLE_FURY_2: 7,
  BATTLE_FURY_3: 8,
  BLOODLUST: 9,
};

export const STATUSES: IStatus[] = [
  {
    id: STATUS_ID.FLEXED,
    name: 'Flexed',
    icon: ICON_ID.STATUS_ATTACK_UP,
    description: 'Increased strength by 30%.',
    duration: 3,
    durationCounter: 3,
    effect: {
      damageBonus: 0,
      incomingDamageReduction: 0,
      damageOverTime: 0,
      strengthMultiplier: 1.3,
      intelligenceMultiplier: 1,
      defenseMultiplier: 1,
      lifesteal: 0,
      canMove: true,
      canAttack: true,
    },
  },
  {
    id: STATUS_ID.PETRIFIED,
    name: 'Petrified',
    icon: ICON_ID.STATUS_PETRIFIED,
    description: 'Cannot move or attack.',
    duration: 3,
    durationCounter: 3,
    effect: {
      damageBonus: 0,
      incomingDamageReduction: 0,
      damageOverTime: 0,
      strengthMultiplier: 1,
      intelligenceMultiplier: 1,
      defenseMultiplier: 1,
      lifesteal: 0,
      canMove: false,
      canAttack: false,
    },
  },
  {
    id: STATUS_ID.STONE_SKIN,
    name: 'Stone Skin',
    icon: ICON_ID.STATUS_DEFENSE_UP,
    description: 'Increased defense by 30%.',
    duration: 3,
    durationCounter: 3,
    effect: {
      damageBonus: 0,
      incomingDamageReduction: 0,
      damageOverTime: 0,
      strengthMultiplier: 0,
      intelligenceMultiplier: 0,
      defenseMultiplier: 1.3,
      lifesteal: 0,
      canMove: true,
      canAttack: true,
    },
  },
  {
    id: STATUS_ID.BURNED,
    name: 'Burned',
    icon: ICON_ID.STATUS_BURNED,
    description: 'Takes 1 damage at the start of the turn.',
    duration: 3,
    durationCounter: 3,
    effect: {
      damageBonus: 0,
      incomingDamageReduction: 0,
      damageOverTime: 1,
      strengthMultiplier: 1,
      intelligenceMultiplier: 1,
      defenseMultiplier: 1,
      lifesteal: 0,
      canMove: true,
      canAttack: true,
    },
  },
  {
    id: STATUS_ID.FROZEN,
    name: 'Frozen',
    icon: ICON_ID.STATUS_FROZEN,
    description: 'Cannot move or attack for 2 turns.',
    duration: 2,
    durationCounter: 2,
    effect: {
      damageBonus: 0,
      incomingDamageReduction: 0,
      damageOverTime: 0,
      strengthMultiplier: 1,
      intelligenceMultiplier: 1,
      defenseMultiplier: 1,
      lifesteal: 0,
      canMove: false,
      canAttack: false,
    },
  },
  {
    id: STATUS_ID.BATTLE_FURY_1,
    name: 'Battle Fury I',
    icon: ICON_ID.STATUS_BATTLE_FURY,
    description: 'Increased strength by 20%. Increased defense by 10%.',
    duration: 3,
    durationCounter: 3,
    effect: {
      damageBonus: 0,
      incomingDamageReduction: 0,
      damageOverTime: 0,
      strengthMultiplier: 1.2,
      intelligenceMultiplier: 1,
      defenseMultiplier: 1.1,
      lifesteal: 0,
      canMove: true,
      canAttack: true,
    },
  },
  {
    id: STATUS_ID.BATTLE_FURY_2,
    name: 'Battle Fury II',
    icon: ICON_ID.STATUS_BATTLE_FURY,
    description: 'Increased strength by 40%. Increased defense by 20%.',
    duration: 3,
    durationCounter: 3,
    effect: {
      damageBonus: 0,
      incomingDamageReduction: 0,
      damageOverTime: 0,
      strengthMultiplier: 1.4,
      intelligenceMultiplier: 1,
      defenseMultiplier: 1.2,
      lifesteal: 0,
      canMove: true,
      canAttack: true,
    },
  },
  {
    id: STATUS_ID.BATTLE_FURY_3,
    name: 'Battle Fury III',
    icon: ICON_ID.STATUS_BATTLE_FURY,
    description: 'Increased strength by 60%. Increased defense by 30%.',
    duration: 3,
    durationCounter: 3,
    effect: {
      damageBonus: 0,
      incomingDamageReduction: 0,
      damageOverTime: 0,
      strengthMultiplier: 1.6,
      intelligenceMultiplier: 1,
      defenseMultiplier: 1.3,
      lifesteal: 0,
      canMove: true,
      canAttack: true,
    },
  },
  {
    id: STATUS_ID.BLOODLUST,
    name: 'Bloodlust',
    icon: ICON_ID.STATUS_BLOODLUST,
    description: 'Convert 50% of any damage dealt into health.',
    duration: 3,
    durationCounter: 3,
    effect: {
      damageBonus: 0,
      incomingDamageReduction: 0,
      damageOverTime: 0,
      strengthMultiplier: 1,
      intelligenceMultiplier: 1,
      defenseMultiplier: 1,
      lifesteal: 0.5,
      canMove: true,
      canAttack: true,
    },
  },
];
